version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: todolist-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    build: .
    container_name: todolist-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/todolist
    depends_on:
      - mongodb

volumes:
  mongo-data:
